// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbj050DXAEGNXalpBfZZPHU3kUzDcu0Xo',
    appId: '1:1038924359065:web:23367d98b83c2b22849f08',
    messagingSenderId: '1038924359065',
    projectId: 'flutter-tmp-dc56d',
    authDomain: 'flutter-tmp-dc56d.firebaseapp.com',
    storageBucket: 'flutter-tmp-dc56d.firebasestorage.app',
    measurementId: 'G-MQ03TCWVEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0353m7KLPsQ1lqaDUwl4PHFflroYJ-0',
    appId: '1:1038924359065:android:3fe3deaf538e751b849f08',
    messagingSenderId: '1038924359065',
    projectId: 'flutter-tmp-dc56d',
    storageBucket: 'flutter-tmp-dc56d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjbrFkEqoaxGMcroE9ZEfuNqL1yCWqPhE',
    appId: '1:1038924359065:ios:5f1d965a729f3f56849f08',
    messagingSenderId: '1038924359065',
    projectId: 'flutter-tmp-dc56d',
    storageBucket: 'flutter-tmp-dc56d.firebasestorage.app',
    iosBundleId: 'com.fox.flutter.tmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjbrFkEqoaxGMcroE9ZEfuNqL1yCWqPhE',
    appId: '1:1038924359065:ios:2e364b2ee1443549849f08',
    messagingSenderId: '1038924359065',
    projectId: 'flutter-tmp-dc56d',
    storageBucket: 'flutter-tmp-dc56d.firebasestorage.app',
    iosBundleId: 'com.fluttertemp.flutterTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbj050DXAEGNXalpBfZZPHU3kUzDcu0Xo',
    appId: '1:1038924359065:web:e86f491d50880331849f08',
    messagingSenderId: '1038924359065',
    projectId: 'flutter-tmp-dc56d',
    authDomain: 'flutter-tmp-dc56d.firebaseapp.com',
    storageBucket: 'flutter-tmp-dc56d.firebasestorage.app',
    measurementId: 'G-9T46C2YY16',
  );

}