// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTWUXyWKigpGJMdiZGXIX8J6cmsX1EF4',
    appId: '1:281391047211:web:f07ffbf78223836ba4806e',
    messagingSenderId: '281391047211',
    projectId: 'fox-firebase-e3b46',
    authDomain: 'fox-firebase-e3b46.firebaseapp.com',
    storageBucket: 'fox-firebase-e3b46.appspot.com',
    measurementId: 'G-4B7M54D683',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUkVMrxXBuXoue8oOa-2yLO0OXmf1edQ',
    appId: '1:281391047211:android:b1e2e1af5507a3b2a4806e',
    messagingSenderId: '281391047211',
    projectId: 'fox-firebase-e3b46',
    storageBucket: 'fox-firebase-e3b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRj5yNEjI_LyCwxl3Z0-XGFXCdBsMfcTE',
    appId: '1:281391047211:ios:f3cba7dd5e1f8bdfa4806e',
    messagingSenderId: '281391047211',
    projectId: 'fox-firebase-e3b46',
    storageBucket: 'fox-firebase-e3b46.appspot.com',
    androidClientId: '281391047211-gni222i8aujo6tjukei8q40k9u1pi6pb.apps.googleusercontent.com',
    iosClientId: '281391047211-3sdtu3i8k1ni3valqi02uphsqiuklt76.apps.googleusercontent.com',
    iosBundleId: 'com.fluttertemp.flutterTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRj5yNEjI_LyCwxl3Z0-XGFXCdBsMfcTE',
    appId: '1:281391047211:ios:f3cba7dd5e1f8bdfa4806e',
    messagingSenderId: '281391047211',
    projectId: 'fox-firebase-e3b46',
    storageBucket: 'fox-firebase-e3b46.appspot.com',
    androidClientId: '281391047211-gni222i8aujo6tjukei8q40k9u1pi6pb.apps.googleusercontent.com',
    iosClientId: '281391047211-3sdtu3i8k1ni3valqi02uphsqiuklt76.apps.googleusercontent.com',
    iosBundleId: 'com.fluttertemp.flutterTemp',
  );
}
